proto_library(
    name = 'market_simulation_proto',
    srcs = ['market_simulation.proto'],
    visibility=['PUBLIC'],
)

proto_library(
    name = 'market_simulation_config_proto',
    srcs = ['market_simulation_config.proto'],
    visibility=['PUBLIC'],
)

